# Generated by Django 3.2.8 on 2021-12-01 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugname', models.CharField(max_length=30)),
                ('is_opioid', models.BooleanField()),
            ],
            options={
                'db_table': 'pd_drugs',
            },
        ),
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('credentials', models.CharField(max_length=30)),
                ('specialty', models.CharField(max_length=62)),
                ('is_opioid_prescriber', models.BooleanField()),
                ('total_prescriptions', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 'pd_prescriber',
            },
        ),
        migrations.CreateModel(
            name='StateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=10, unique=True)),
                ('stateabbrev', models.CharField(blank=True, max_length=2)),
                ('population', models.IntegerField(blank=True, default=0)),
                ('deaths', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 'pd_statedata',
            },
        ),
        migrations.CreateModel(
            name='Triple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('drugname', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='homepages.drugs', verbose_name='Drugs')),
                ('prescriber_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='homepages.prescriber', verbose_name='Prescriber')),
            ],
            options={
                'db_table': 'pd_triple',
            },
        ),
        migrations.AddField(
            model_name='prescriber',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='homepages.statedata', verbose_name='State'),
        ),
    ]
