# Generated by Django 3.2.8 on 2021-12-02 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drugid', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('drugname', models.CharField(max_length=30, unique=True)),
                ('isopioid', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'pd_drugs',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state', models.CharField(blank=True, max_length=10, unique=True)),
                ('stateabbrev', models.CharField(blank=True, max_length=2, primary_key=True, serialize=False, unique=True)),
                ('population', models.IntegerField(blank=True, default=0)),
                ('deaths', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 'pd_statedata',
            },
        ),
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('npi', models.IntegerField(blank=True, default=0, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('credentials', models.CharField(max_length=30)),
                ('specialty', models.CharField(max_length=62)),
                ('isopioidprescriber', models.CharField(max_length=5)),
                ('totalprescriptions', models.IntegerField(blank=True, default=0)),
                ('state', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='homepages.state', verbose_name='State')),
            ],
            options={
                'db_table': 'pd_prescriber',
            },
        ),
        migrations.CreateModel(
            name='Triple',
            fields=[
                ('drugid', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='homepages.drug', verbose_name='Drugs')),
                ('qty', models.IntegerField(blank=True, default=0)),
                ('prescriber_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='homepages.prescriber', verbose_name='Prescriber')),
            ],
            options={
                'db_table': 'pd_triple',
            },
        ),
    ]
