# Generated by Django 3.2.8 on 2021-12-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drugs',
            new_name='Drug',
        ),
    ]
